### PR TITLE
smartEdit should pass command output to callback

### PR DESCRIPTION
**Pull request by yangchenyun**

### CODE REVIEW

**Comment by natelong** [comment]
Great change. Thanks!

**Comment by yangchenyun** [comment]
Thanks for the original work! Will there be a minor release for this patch soon?

**Comment by natelong** [comment]
Ha! Good call. I'll get that up soon. Thanks for the reminder :)

**Comment by natelong** [comment]
Done and done. Thanks again!

**Comment by yangchenyun** [comment]
Awesome! Thanks :+1:

**Pull request merged**
